#!/bin/bash

NAME=$1
NR=$(echo $NAME | egrep -o '[0-9][0-9]$')
P=$$
LANG=C
TPD=/srv/vm/datastores/templates
VMD=/srv/vm/datastores/vms

if [ $# -lt 3 ] ; then 
  MEMORY=3145728
  VCPU=2
else
  MEMORY=$3
  VCPU=$2
fi



echo $NAME | egrep -q '^vm[0-9][0-9]$' || (echo Usage: $(basename $0) vmNN ; kill -9 $P )
virsh list --all | grep $NAME && (echo ERROR: $NAME exists ; kill -9 $P )
echo "INFO: Create CentOS 8 VM: $NAME"

  set -e
  MYUUID=$(uuidgen)
  cd $TPD
  cp -av template_cos8.qcow2 $VMD/$NAME.qcow2
  sed "s/__NAME__/$NAME/g" template_cos8.xml > $NAME.xml
  sed -i "s/__NR__/$NR/g" $NAME.xml
  sed -i "s/__UUID__/$MYUUID/g" $NAME.xml
  sed -i "s/__DISK1__/$NAME.qcow2/g" $NAME.xml
  sed -i "s/__MEMORY__/$MEMORY/g" $NAME.xml
  sed -i "s/__VCPU__/$VCPU/g" $NAME.xml
 # sed -i "s/__DISK2__/${NAME}_2.qcow2/g" $NAME.xml
  virsh define $NAME.xml > /dev/null
  rm -f $NAME.xml
  virsh start $NAME

