#!/bin/bash

NAME=$1
P=$$
LANG=C

echo $NAME | egrep -q '^vm[0-9][0-9]$' || (echo Usage: $(basename $0) vmNN ; kill -9 $P )

if [[ $2 != "--now" ]] ; then
  virsh list | grep $NAME && (echo ERROR: $NAME running ; kill -9 $P )

  echo "GOING TO DESTROY $NAME"
  echo "ctrl-c now!"
  sleep 5
else
  vm-stop $NAME --now > /dev/null 2>&1
fi

virsh undefine $NAME > /dev/null
rm -f /srv/vm/datastores/vms/$NAME.qcow2
