#!/bin/bash

NAME=$1
P=$$
LANG=C

echo $NAME | egrep -q '^[a-z]+[0-9]{2}$' || (echo Usage: $(basename $0) vmNN ; kill -9 $P )
virsh list | grep $NAME && (echo ERROR: $NAME running ; kill -9 $P )

virsh start $NAME > /dev/null
